# Generated by Django 4.2.27 on 2026-01-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phome_number',
            new_name='phone_number',
        ),
    ]
